### ISSUE TITLE
Need for a "<Chip/>" component. 

### ISSUE THREAD

**Issue by DhirajBhakta** [fictoan/fictoan-react#27]
[Material Example](https://material-ui.com/components/chips/)

**Comment by sujan-s** [comment]
```
<Button size="tiny" shape="curved" bgColour="someColour" textColour="someColour">
    Some text
</Button>
```

![Screenshot 2020-07-08 at 6 40 33 PM](https://user-images.githubusercontent.com/19920532/86922594-8321ea00-c14a-11ea-95eb-1e8c796b131d.png)
