### ISSUE TITLE
Investigate bundle size reduction

### ISSUE THREAD

**Issue by sujan-s** [fictoan/fictoan-react#42]
Need to find ways to reduce final bundle size. Right now, it is—

403kB minified
108.7kB minified + GZipped

3.62s on 2G EDGE
2.17s on emerging 3G

**Comment by sujan-s** [comment]
@dhruvmisra @ghostwriternr any ideas?

**Comment by dhruvmisra** [comment]
Big improvements after #50:

254.7kB minified
73.5kB minified + GZipped
\+  tree-shakable build (https://bundlephobia.com/package/fictoan-react@0.33.3)
